version: '2.1'

orbs:
  gcp-cli: circleci/gcp-cli@3.2.1

parameters:
  image-name:
    type: string
    default: asia-northeast1-docker.pkg.dev/$GOOGLE_PROJECT_ID/server/backend-ha-suzuki

commands:
  gcloud-authentication:
    steps:
      - gcp-cli/setup:
          gcloud_service_key: GCLOUD_SERVICE_KEY
          google_project_id: GOOGLE_PROJECT_ID

jobs:
  build-backend:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout
      - run:
          name: Docker Build
          working_directory: ~/project/backend/
          command: docker build -t backend-ha-suzuki .
      - gcloud-authentication
      - run:
          name: Docker Images
          command: docker images
      - run:
          name: Docker Configure
          command: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - run:
          name: Docker Push
          command: |
            docker tag backend-ha-suzuki asia-northeast1-docker.pkg.dev/tech-induction-training-2024/server/backend-ha-suzuki
            docker push asia-northeast1-docker.pkg.dev/$GOOGLE_PROJECT_ID/server/backend-ha-suzuki
      - run:
          name: Deploy
          command: gcloud run deploy service-backend-ha-suzuki --image asia-northeast1-docker.pkg.dev/tech-induction-training-2024/server/backend-ha-suzuki:latest --region asia-northeast1 --allow-unauthenticated
    
  build-frontend:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout
      - run:
          name: Docker Build
          working_directory: ~/project/frontend/
          command: docker build -t frontend-ha-suzuki .
      - gcloud-authentication
      - run:
          name: Docker Images
          command: docker images
      - run:
          name: Docker Configure
          command: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - run:
          name: Docker Push
          command: |
            docker tag frontend-ha-suzuki asia-northeast1-docker.pkg.dev/tech-induction-training-2024/server/frontend-ha-suzuki
            docker push asia-northeast1-docker.pkg.dev/$GOOGLE_PROJECT_ID/server/frontend-ha-suzuki
      - run:
          name: Deploy
          command: gcloud run deploy service-frontend-ha-suzuki --image asia-northeast1-docker.pkg.dev/tech-induction-training-2024/server/frontend-ha-suzuki:latest --region asia-northeast1 --allow-unauthenticated



workflows:
  install_and_configure_cli:
    jobs:
      - build-backend
      - build-frontend
