version: '2.1'

orbs:
  gcp-cli: circleci/gcp-cli@3.2.1

commands:
  gcloud-authentication:
    steps:
      - gcp-cli/setup:
          gcloud_service_key: GCLOUD_SERVICE_KEY
          google_project_id: GOOGLE_PROJECT_ID

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout
      - run:
          name: Docker Build
          working_directory: ~/project/backend/
          command: docker build -t node:22-slim .
      - gcloud-authentication
      - run:
          name: Docker Images
          command: docker images
      - run:
          name: Docker Push
          command: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
    
    # deploy:
    #   machine:
    #     image: ubuntu-2204:current
    #   resource_class: large
    #   steps:
    #     - checkout
    #     - run:
    #         name: Docker Build
    #         working_directory: ~/project/backend/
    #         command: docker build -t node:22-slim .


workflows:
  install_and_configure_cli:
    jobs:
      - build
